#!/bin/tcsh

#set DEFAULT_DESIGN = "cnt_bits"
#set DEFAULT_DESIGN = "fifo"
#set DEFAULT_DESIGN = "ring_buf"
#set DEFAULT_DESIGN = "cam"
#set DEFAULT_DESIGN = "shifter"
#set DEFAULT_DESIGN = "regfile"
#set DEFAULT_DESIGN = "freelist"
#set DEFAULT_DESIGN = "selector"
#set DEFAULT_DESIGN = "sel_minmax"
#set DEFAULT_DESIGN = "stack"
#set DEFAULT_DESIGN = "reduct"
#set DEFAULT_DESIGN = "gather"
#set DEFAULT_DESIGN = "scatter"
#set DEFAULT_DESIGN = "block_shift"
set DEFAULT_DESIGN = "ram"
